---
name: Copy Edit
description: Issue with spelling, grammar, or clarify of writing
body:
- type: markdown
  attributes:
    value: "# Copy Edit Form"
- type: markdown
  attributes:
    value: |
      A **copy edit** issue should be made where you identify a writing error in the text. This can be a typo, formatting error, or an issue with our syntax.
- type: markdown
  attributes:
    value: |
      Please provide information around the nature of the copy edit request you have by filling out the remainder of this form. The more information you provide, the more likely we will be able to resolve the issue.
- type: textarea
  attributes:
    label: "Permalink: Path to Issue"
    placeholder: (Which page is the problem on? Copy the permalink to the closest subheading *above* the issue by clicking on the ¶ symbol next to that heading.)
  validations:
    required: true
- type: textarea
  attributes:
    label: Issue to be fixed
    placeholder: "What's the problem? Be as specific as possible."
  validations:
    required: true
- type: textarea
  attributes:
    label: More information
    placeholder: "Provide any additional information we may need to fix the issue. If helpful, add a screenshot."
- type: markdown
  attributes:
    value: "# Thank You"
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to help us in improving this course. You rock!
- type: markdown
  attributes:
    value: "### Disclaimer"
- type: markdown
  attributes:
    value: |
      We value all the input received from our students, course staff, and allies of LaunchCode. However, all issues will be considered by LaunchCode staff before issue resolution. LaunchCode reserves the final say on bug fixes, clarity improvements, and new features. We offer no guarantee that any issues will result in changes to the curriculum.
      